### ISSUE TITLE
[1.14.3] Suggestion/request

### ISSUE THREAD

**Issue by kwpugh** [KillerMapper/embellishcraft#1]
Hi, 

I am the author of the Gobber mod.   I have an item called the Ring of the Miner, that clears away vanilla stone and such, leaving ores exposed for mining.   

I was wondering if you would consider tagging your Basalt, Slate, Marble, Gneiss with the Forge tag "STONE" so that I can easily identify them with if(Block.isRock()?

isRock checks: net.minecraftforge.common.Tags.Blocks.STONE.contains(blockIn);

If you can add the forge tags to those 4 blocks, it would make life a lot easier.

This would be a great help.

Thank you for considering.

Regards.

**Comment by KillerMapper** [comment]
Hello, yes this is planned, I didn't assign the tags yet (except for the walls as it's mandatory for them to work). It will be done in the next version.

**Comment by kwpugh** [comment]
Thank you very much.   I enjoy playing you mod in my modpack.   This will make things work very nicely.

Regards

**Comment by KillerMapper** [comment]
Version 0.0.2.1 adds the tags. It is available on Curse.

**Comment by kwpugh** [comment]
Thank you.  I will check it out.

**Comment by kwpugh** [comment]
I tested it out and it works beautifully.  Thank you.

One line of code:   Block.isRock(block) == true

Boom.
