### ISSUE TITLE
Not an issue but maybe a cleaning stuff

### ISSUE THREAD

**Issue by f0kx** [KillerMapper/EmbellishCraft#10]
Hey when i open JEI your items are in a very confusing order! is that intended!

![image](https://user-images.githubusercontent.com/14795020/76812013-d7980700-67f3-11ea-8986-fef016ae6c80.png)

**Comment by f0kx** [comment]
When i create a new world than all is fine 

![image](https://user-images.githubusercontent.com/14795020/76855053-97b33d00-6850-11ea-9830-bbb8223029cd.png)

But can you explain how i can fix this

**Comment by MapperTV** [comment]
Not a bug. This is just how Forge assigns IDs to blocks and items. When a new world is created, it assigns them mod by mod, in the order the blocks and items are registered in each mod (in my case I register by block, stairs, slab... for each block, this is why it looks like this on your second screen). If you add a mod on an existing world, its blocks and items will just have randomly assigned IDs. This changes nothing on mod contents or stability.

**Comment by f0kx** [comment]
so i cant do something about it that items are confused in order?
Because its so ugly to search what i can craft and what color is available

**Comment by MapperTV** [comment]
Only way is to create a new save.

**Comment by f0kx** [comment]
This is a multiplayer server. 
Is there a solution

**Comment by MapperTV** [comment]
No.
