### ISSUE TITLE
cant open single inventories(bug with the mod or library)

### ISSUE THREAD

**Issue by SDUBZ** [KillerMapper/EmbellishCraft#13]
https://gist.githubusercontent.com/SDUBZ/3081f3d9a59b852cda4eb28a77b59177/raw/6023dd7e84606ff29aacc7353d342ca7aeec25b5/latest.log

Forge: 31.1.36
mapperbase-1.15.2-1.0.0.1.jar
embellishcraft-1.15.2-2.1.0.1.jar

**Comment by MapperTV** [comment]
Can you provide more information? What did you do, what did you try to open etc. I can't reproduce the issue.

**Comment by SDUBZ** [comment]
i just placed down a single chest and it gave the menu screen but onyl when your mod was installed went away as soon as i disabled your mod and library
did you test oustside your dev enviroment ?

**Comment by MapperTV** [comment]
Yes I always test with some other mods, but there are too many mods around so I can't test with all of them.

Is the modpack you're playing available somewhere? It's possible that it is a conflict with another mod. I've trying with Botania, Mekanism, RFtools and few other mods but couldn't reproduce it yet. It's too long to gather all the mods.

**Comment by SDUBZ** [comment]
this one is kinda in dev not public yet but i will make a public version
very soon since its related to skyblock kinda hard atm the with no quest
mods etc
