### ISSUE TITLE
[1.15.2] Biome Blacklist for Stonetype Generation

### ISSUE THREAD

**Issue by TheUntamed** [KillerMapper/EmbellishCraft#15]
Could you add a config option to set a biome blacklist/whitelist for dach of the Stone Types?

**Comment by MapperTV** [comment]
Will be in next version.

**Comment by MapperTV** [comment]
Released in 2.1.1.0.

https://www.curseforge.com/minecraft/mc-mods/embellishcraft/files/2934650
