### ISSUE TITLE
[Suggestion] New texture for fancy doors.

### ISSUE THREAD

**Issue by Matthysse** [KillerMapper/EmbellishCraft#16]
Hello !
I have a small suggestion : I don't really like the fancy doors it looks like a texture pack, it doesn't fit well in Minecraft. 
The texture I will show is not mine (but it isn't copyrighted, it was created by a youtuber in 2013 just for a modpack and he doesn't claim it as his texture) but I would love to see something like this. It would work really well for interiors.
![fancy_door](https://user-images.githubusercontent.com/32510957/79560279-9cfde480-80a7-11ea-9a42-3127b881ecf1.png)

**Comment by f0kx** [comment]
i also want to suggest a other texture for the fancy doors! 

but my suggestion was to do a glas door with the wood

https://imgur.com/a/cOlZB5E
