### ISSUE TITLE
[1.15.2] Recipes using vanilla stones create conflicts with other mods.

### ISSUE THREAD

**Issue by thecanidcoder** [KillerMapper/EmbellishCraft#23]
For example, the recipe to cook Granite into Smooth Granite in a Furnace. Another mod I use has the same recipe with a different output; as neither mod has a config option for this, I'm forced to come up with my own methods of resolving it.

A config option to disable or provide an alternate for recipes using vanilla stones would be appreciated.

**Comment by MapperTV** [comment]
Minecraft already comes with a tool to resolve conflicts: JSON recipe files. You can change recipes using them including smelting recipes, this way it is possible to resolve conflicts.

https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack
https://minecraft.gamepedia.com/Recipe#JSON_format

If you use a modpack then contact its author to ask for custom recipes to resolve the issue.
