### ISSUE TITLE
[1.16.3] Need update due to forge changes - IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.

### ISSUE THREAD

**Issue by ProsperCraft** [KillerMapper/EmbellishCraft#25]
Forge: forge-34.1.29
Log-
https://gist.github.com/ProsperCraft/a65b7d86faec80e663b8679c7c8b4e66
Crash log-
https://gist.github.com/ProsperCraft/574b2291310d86ee45aedad4cf93b42b

**Comment by MaxGGx** [comment]
Having the same issue with latest forge version (34.1.32)
Here's the log:
-https://drive.google.com/file/d/1Eth8WqWoIPT9i_trtj9n4rX0ojGaIAUE/view?usp=sharing
And crash log:
-https://drive.google.com/file/d/1FZNOb_RE85mOUdw9GRBJGanHSLfOKolP/view?usp=sharing

I've found a temporally solution by installing an older version of forge, I tried with the version 34.1.0 and the error dissapears.

**Comment by MapperTV** [comment]
I'll make a new version to fix the problem.

**Comment by P3rf3ctXZer0** [comment]
Cannot update server because I have the same issue and I will get large holes in the world if I remove your mod.

**Comment by lulabyte** [comment]
> 
> 
> I'll make a new version to fix the problem.

Thanks so much!

**Comment by ProsperCraft** [comment]
This is the last mod that needs to update, I just removed blue power because they are not updating, but I can't remove this one, it is too nice for town building :)

Thank you for looking at updating.

**Comment by MapperTV** [comment]
I released a new version, should fix the problem. If not then report it here.
You need Forge 34.1.34 or newer to make it work (Forge team released 34.1.35 when I was building my mods).

**Comment by ProsperCraft** [comment]
It looks good, except now it appears forge made more breaking changes-
https://github.com/Darkhax-Minecraft/Tips/issues/22
