### ISSUE TITLE
Embellishcraft 1.16.3-3.2.0.0 Crashes Forge server on load.

### ISSUE THREAD

**Issue by judicius** [KillerMapper/EmbellishCraft#26]
MC 1.16.4
Forge 35.1.4
Embellishcraft 1.16.3-3.2.0.0

Server Crashes while starting

https://pastebin.com/XJW1w2tc

**Comment by MapperTV** [comment]
Possible change breaking from Forge 1.16.4. Will check. I plan to release a new version for 1.16.4 anyways.

**Comment by MapperTV** [comment]
I released 1.16.4 versions so this shouldn't be a problem anymore.
