### ISSUE TITLE
Required Mapperbase adds too much

### ISSUE THREAD

**Issue by Zygus42** [KillerMapper/EmbellishCraft#27]
Your required mod mapperbase adds steel manufacturing and all kinds of steel items.  This will not work in my modpack as it conflicts with much more hard to do steel manufacturing. 

Would be a shame to not be able to use this great deco mod because of the required common mod.  

Surely all of this should be in a separate mod instead of in a common required mod ?  Could you at least please add a config to mapperbase that allows for the switching off of the steel manufacturing ?

**Comment by MapperTV** [comment]
You can now change or disable the recipe using the [JSON system Minecraft introduced in 1.13](https://minecraft.gamepedia.com/Recipe#JSON_format). Configs are not needed anymore as this is how recipes can be tweaked now, at least for recipes using Minecraft systems (like basic crafting, furnaces...). Alternatively you can remove the steel from the associated tags so it can't be used anymore in recipes but it will still let players craft it while it will be useless.

> Surely all of this should be in a separate mod instead of in a common required mod ?

Yes, and this mod is Mapper Base. Steel is used in my other mods so I created this mod to avoid implementing multiple steel in all my other mods.

For now the only thing that can't be changed is the values for steel gear (tools, weapon, armor). I plan to add a config for this.
