### ISSUE TITLE
1.16.5 server crash on load

### ISSUE THREAD

**Issue by SDUBZ** [KillerMapper/EmbellishCraft#29]
forge : 1.16.5-36.0.10

ec: embellishcraft-1.16.4-3.3.0.0

log:
[latest.log](https://github.com/MapperTV/embellishcraft/files/5897628/latest.log)
[debug.log](https://github.com/MapperTV/embellishcraft/files/5897629/debug.log)

crash:
[crash-2021-01-30_03.44.25-fml.txt](https://github.com/MapperTV/embellishcraft/files/5897627/crash-2021-01-30_03.44.25-fml.txt)

**Comment by MapperTV** [comment]
Can you update Forge and see if it works? 0.10 may have some issue. Just tried with 0.13 and it works fine on both client and server.

**Comment by SDUBZ** [comment]
everything is working all good now
