### ISSUE TITLE
Table lamps toggable by hand, Abnormals addon and wall lamp

### ISSUE THREAD

**Issue by Matthysse** [KillerMapper/EmbellishCraft#31]
Hello!
Could you add the ability to toggle the table lamp on/off with the hand, and not just with a redstone signal? Because I love the "on" texture, but we need to put a lever to have it.

It would be nice if you could add a Abnormals addon, with all the woods from Environmental, Automnity, Abundance, Bayou Blues, Atmospheric etc. because they tend to slowly replace Biomes O Plenty (I personally don't use it anymore)

Lastly, why not adding a Wall Lamp? It would have the style of the table lamp, but with a support for the walls. So why not renaming Table Lamp into "Interior Lamp" that would, if you click on the ground place a table lamp, and if placed on the walls place a wall lamp.

**Comment by MapperTV** [comment]
Manual table lamps are now added in 3.4.0.0. Right click to toggle them.

More lamps are in the plans for a while so eventually they will come in a future version.
For addons I'll see what I can do.
