### ISSUE TITLE
[Feature Request] Cobblestone brick/Quark support for stone variants

### ISSUE THREAD

**Issue by Seth0067** [KillerMapper/EmbellishCraft#32]
Love the mod!  Thank you for it.

Quark allows users to create a new block, cobblestone bricks, by placing 2x2 cobble in a grid. These are great early construction blocks and look pretty rad.

Support for all the new cobble types within Embellishcraft would be really amazing. Probably not too hard to do, and would be great mod cross-compatibility.  If you think this is a good idea, and would like help with creating the assets (provided you don't do this programmatically using one greyscale tile and a color palette id), I can perhaps even do this after 4-10 (when i finish moving). The programmatic solution is probably a better way to go, but just wanted to offer what I could. :)

Keep up the great contributions to the community!

**Comment by MapperTV** [comment]
Added in 3.4.0.0.

Note: does not require Quark to be installed.
