### ISSUE TITLE
Suspended stair blocks don't init the waterlogged property

### ISSUE THREAD

**Issue by desht** [KillerMapper/EmbellishCraft#33]
I noticed that your suspended stair blocks don't set blockstate property defaults in their constructor.  This may also apply to other blocks of yours, but I noticed it here.

The upshot of this is that the property value on block placement is indeterminate, and while I'm guessing it gets init'd elsewhere for manual placement since that works OK, this is what happens if you try and copy/paste some of your stairs with Direwolf's Building Gadgets copy/paste tool:

![2021-04-26_12 23 39](https://user-images.githubusercontent.com/736831/116074999-5794cf80-a68a-11eb-8dab-88ce06c1bd91.png)

The fix would be to add:
```java
setDefaultState(getStateContainer().getBaseState().with(WATERLOGGED, false));
```
in the block's constructor (possibly defaulting any other properties here too).

**Comment by MapperTV** [comment]
This will be fixed in next release. If you find other blocks having issues please list them here. I checked a bit on my side and didn't find any problem outside of lockers not having a tile entity (no idea why, will try to see).
