### ISSUE TITLE
[1.16.5] Error during the common_setup event phase

### ISSUE THREAD

**Issue by Zothen1973** [KillerMapper/EmbellishCraft#34]
Hello,

I get this error more often than usual lately. Not always.

Minecraft 1,16,5 Forge 36.1.9 250+ Mods

![grafik](https://user-images.githubusercontent.com/77007295/116967248-2d5a9780-acb2-11eb-980d-7782395a8af4.png)

[crash-2021-05-04_08.19.44-fml.txt](https://github.com/MapperTV/embellishcraft/files/6419292/crash-2021-05-04_08.19.44-fml.txt)
[latest.log](https://github.com/MapperTV/embellishcraft/files/6419293/latest.log)

**Comment by MapperTV** [comment]
This may be similar to #19 and I still didn't found why it randomly crashes. I'm releasing a new version soon using Forge 1.16.5, maybe this will change something.
