### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by judicius** [KillerMapper/EmbellishCraft#35]
MC 1.16.5
Forge 36.1.31
Embelliscraft: 3.4.0.0

https://gist.github.com/judicius/596cb8f9f44715cb04c648445b571d6c

restart didn't repeat the error. Hope this helps you track this bug down.

**Comment by MapperTV** [comment]
Duplicate of #19 

It's a bug randomly happening for more than a year now and couldn't find the reason yet as there is no defined pattern to make it occur.
