### ISSUE TITLE
Villagers do not go downstairs properly (suspended stairs)

### ISSUE THREAD

**Issue by emanuele246gi** [KillerMapper/EmbellishCraft#36]
When they follow their pathway and there is a suspended stair to run across, they will block on it and run around on themselves
![2021-07-18_16 57 24](https://user-images.githubusercontent.com/61762317/126071967-31099194-53cf-4756-ad2f-57ccefc00506.png)

(I know that the image doesn't move, but I tried to show it somehow lol)

**Comment by MapperTV** [comment]
Doe this happens with Minecraft stairs too? The suspended stairs use the same collision mesh than regular Minecraft stairs so I don't see what can be done to avoid this problem. It may just be Minecraft handling stairs badly.

**Comment by emanuele246gi** [comment]
No, with vanilla stairs it's fine, but with these they keep spinning

**Comment by MapperTV** [comment]
I released a new version that fixes this issue. For now it's still 1.18.1 but 1.18.2 will be done as soon as possible.
