### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by Catomax262** [KillerMapper/EmbellishCraft#42]
https://bytebin.lucko.me/AqpLWWXooc

Also crashed with Road Stuff

**Comment by McJty** [comment]
It's crashing in the 'rsgauges' mod. Not an embellishcraf tissue

**Comment by Catomax262** [comment]
Probably bc it's now unsupported, but the same happened with wooden shield from spartan shields

**Comment by Catomax262** [comment]
Also happens the same error with Road Stuff, Embellishcraft and others
